// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesHolland.Models;

namespace RazorPagesHolland.Migrations
{
    [DbContext(typeof(RazorPagesHollandContext))]
    [Migration("20190124215616_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RazorPagesHolland.Models.Holland", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DiveDate");

                    b.Property<string>("Location");

                    b.Property<string>("MapUrl");

                    b.Property<string>("ROVDiveName");

                    b.Property<string>("VesselName");

                    b.Property<string>("VideoUrl");

                    b.HasKey("ID");

                    b.ToTable("Holland");
                });
#pragma warning restore 612, 618
        }
    }
}
