// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesHolland.Models;

namespace RazorPagesHolland.Migrations
{
    [DbContext(typeof(RazorPagesHollandContext))]
    partial class RazorPagesHollandContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RazorPagesHolland.Models.Holland", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DiveDate");

                    b.Property<float>("Latitude")
                        .HasColumnType("float(10, 6)");

                    b.Property<string>("Location");

                    b.Property<float>("Longitude")
                        .HasColumnType("float(10, 6)");

                    b.Property<string>("ROVDiveName");

                    b.Property<string>("VesselName");

                    b.Property<string>("VideoUrl");

                    b.HasKey("ID");

                    b.ToTable("Holland");
                });
#pragma warning restore 612, 618
        }
    }
}
